analyzers:
  ros__parameters:
    path: Mark2.1
    Sensors:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Sensors
      contains: [ 'Sensor' ]
    Main:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Main
      contains: [ 'Status' ]
